/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client\public\sailingship.glb -o client\src\game\SailingShipModel.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['tripo_node_5d6e96c3-b641-40fc-ac79-e09aa75b20bd']: THREE.Mesh
  }
  materials: {
    ['tripo_material_5d6e96c3-b641-40fc-ac79-e09aa75b20bd']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function SailingShip(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/sailingship.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_5d6e96c3-b641-40fc-ac79-e09aa75b20bd'].geometry} material={materials['tripo_material_5d6e96c3-b641-40fc-ac79-e09aa75b20bd']} rotation={[0, -0.715, 0]} />
    </group>
  )
}

useGLTF.preload('/sailingship.glb')
